{{- if .Values.externalSecrets.dynatraceSecrets.enabled -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: user-keyvault
    kind: ClusterSecretStore
  # target.name defines the name of the Kubernetes secret to be created.
  target:
    name: {{ include "dynatrace.fullname" . }}-external-secret-operator-api
    creationPolicy: Owner
  data:
    {{- range $k, $v := .Values.externalSecrets.dynatraceSecrets.secrets }}
    - secretKey: apiToken
      remoteRef:
        key: {{ $v.remoteRef }}
        # version is the secret version from the Azure key vault
        {{- if $v.version }}
        version: {{ $v.version }}
        {{- end }}
    {{- end }}
{{ end }}