{{- if .Values.pushSecrets.wildcardTlsCert.enabled -}}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ include "cert-manager.fullname" . }}-pushsecret
  namespace: {{ include "cert-manager.fullname" . }} # Define the correct namesace
  labels:
    {{- include "cert-manager.labels" . | nindent 4 }}
spec:
  refreshInterval: 10s # Refresh interval for which push secret will reconcile
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: user-keyvault
      kind: ClusterSecretStore
  selector:
    secret:
      name: {{ .Values.pushSecrets.wildcardTlsCert.targetName }} # Source Kubernetes secret to be pushed
  data:
    - match:
        secretKey: tls.key # Source Kubernetes secret key to be pushed
        remoteRef:
          remoteKey: {{ include "cert-manager.fullname" . }}-{{ .Values.pushSecrets.wildcardTlsCert.secretKeys.tlsKey }} # Remote reference (where the secret is going to be pushed)
    - match:
        secretKey: tls.crt # Source Kubernetes secret key to be pushed
        remoteRef:
          remoteKey: {{ include "cert-manager.fullname" . }}-{{ .Values.pushSecrets.wildcardTlsCert.secretKeys.tlsCrt }} # Remote reference (where the secret is going to be pushed)

{{ end }}
