proxy_cache_path /var/cache/nginx levels=1:2
    keys_zone=STATIC:10m
    inactive=24h
    max_size=1g;

limit_req_zone $binary_remote_addr zone=RATE_LIMIT:10m rate=10r/s;

server {
    listen 80;
    server_name devops-example.com www.devops-example.com;

    location / {
        limit_req zone=RATE_LIMIT burst=20 nodelay;

        proxy_cache STATIC;
        proxy_cache_valid 200 301 302 10m;
        proxy_cache_use_stale error timeout updating;

        add_header X-Cache-Status $upstream_cache_status;

        proxy_pass https://your-username.github.io;
        proxy_set_header Host your-username.github.io;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
