include:
  - project: "infrastructure-applications/infrastructure-includes/semantic-release"
    ref: main
    file: "job-templates.yml"

stages:
  - pre-check
  - build
  - deploy
  - prepare-release

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never # Do not run merge request pipelines.
    - when: always # Run all other pipeline types, or replace with specific workflow rules.

tag_release-dryrun:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

tag_release:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /backport\//
